services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: learn-workflow-server:latest
    container_name: learn-workflow-server
    env_file:
      - ./src/.env
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./src:/usr/src/app:cached
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev
    restart: unless-stopped
